# Generated by Django 3.0.6 on 2023-02-13 08:57

from django.db import migrations, models
import vulModel.models


class Migration(migrations.Migration):

    dependencies = [
        ('vulModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to=vulModel.models.user_directory_path)),
                ('upload_method', models.CharField(max_length=50, verbose_name='Upload Method')),
            ],
        ),
    ]
